config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources :users, :places, :dives

  get '/logout' => 'sessions#destroy', as: :logout
  post '/sessions' => 'sessions#create'
  get '/sessions/new' => 'sessions#new', as: :new_session

end

app/models/dive.rb
class Dive < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :dives
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_secure_password
  has_many :dives
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end

  def is_current_user?

  end
end

app/controllers/dives_controller.rb
class DivesController < ApplicationController
  def index
    @dives = Dive.all
  end

  def show
    @places = Place.all
    
    @dive = Dive.find(params[:id])
  end

  def new
    @dive = Dive.new
  end

  def create
    if @dive = current_user.dives.new(dive_params)
        @dive.save
      redirect_to dives_path
    else
      redirect_to root_path
    end
  end

  def edit
    @dive = Dive.find(params[:id])
  end

  def update
    @dive = Dive.find(params[:id])
    if @dive.update_attributes(dive_params)
      redirect_to dive_path @dive
    else
      redirect_to edit_dive_path @dive
    end
  end

  def destroy
    @dive = Dive.find(params[:id])
    @dive.destroy
    redirect_to dives_path
  end

  private
  def dive_params
    params.require(:dive).permit(:number, :date, :timein, :timeout, :depth, :bottom_time, :air_start, :air_end, :nitrox, :temperature, :weight, :computer)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to places_path
    else
      redirect_to root_path
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])

    if @place.update_attributes(place_params)
      redirect_to place_path(@place)
    else
      redirect_to edit_place_path(@place)
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end

  private
  def place_params
    params.require(:place).permit(:city, :sites)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by({email: params[:email]})
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome. Thanks for logging in!"
      redirect_to user_path(@user)
    else
      flash[:failure] = "Oops...something went wrong, please try again."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      redirect_to root_path
    end
  end

  def edit
    if current_user.id.to_s == params[:id]
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    if current_user.id.to_s == params[:id]
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    else
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :certification, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dives_helper.rb
module DivesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dives/edit.html.erb
<div class="container">
  <h1><center>EDIT THIS DIVE</center></h1>

  <%= form_for @dive do |f| %>
    <div>
      <%= f.label :number, 'Dive #' %>
      <%= f.number_field :number %>
    </div>

    <div>
      <%= f.label :date, 'Date' %>
      <%= f.date_field :date %>
    </div>

    <div>
      <p> Dive Site <%= f.collection_select(:place_id, Place.all, :id, :sites) %> </p>
    </div>

    <div>
      <%= f.label :timein, 'Time In' %>
      <%= f.time_field :timein %>
    </div>

    <div>
      <%= f.label :timeout, 'Time Out' %>
      <%= f.time_field :timeout %>
    </div>

    <div>
      <%= f.label :depth, 'Max. Depth in feet' %>
      <%= f.number_field :depth %>
    </div>

    <div>
      <%= f.label :air_start, 'Starting Air PSI' %>
      <%= f.number_field :air_start %>
    </div>

    <div>
      <%= f.label :air_end, 'Ending Air PSI' %>
      <%= f.number_field :air_end %>
    </div>

    <div>
      <%= f.label :nitrox, 'Nitrox' %>
      <%= f.number_field :nitrox %>
    </div>

    <div>
      <%= f.label :temperature, 'Temperature' %>
      <%= f.number_field :temperature %>
    </div>

    <div>
      <%= f.label :weight, 'Weight' %>
      <%= f.number_field :weight %>
    </div>

    <div>
      <%= f.label :computer, 'Dive Computer' %>
      <%= f.text_field :computer %>
    </div>

    <div>
      <%= f.submit "Submit changes" %>
    </div>
  <% end %>
</div>

app/views/dives/index.html.erb
<div class="container">
  <h1><center>LIST OF DIVES</center></h1>
  <center><%= link_to "Add new Dive", new_dive_path %></center>

  <center>
  <% @dives.reverse.each do |d| %>
    <h3><%= link_to d.number, dive_path(d) %>
      <%= d.date.strftime('%d %b %y') %>
      <%= d.place.sites %></h3>

    <h4>Bottom time: <%= ((d.timeout - d.timein)/60).to_i %> min. |
      Max. depth of <%= d.depth %> feet
    <hr>
  <% end %>
</center>
</div>

app/views/dives/new.html.erb
<div class="container">
  <h1><center>ADD NEW DIVE</center></h1>

  <%= form_for @dive do |f| %>
    <div>
      <%= f.label :number, 'Dive #' %>
      <%= f.number_field :number %>
    </div>

    <div>
      <%= f.label :date, 'Date' %>
      <%= f.date_field :date %>
    </div>

    <div>
      <p> Dive Site <%= f.collection_select(:place_id, Place.all, :id, :sites) %> </p>
    </div>

    <div>
      <%= f.label :timein, 'Time In' %>
      <%= f.time_field :timein %>
    </div>

    <div>
      <%= f.label :timeout, 'Time Out' %>
      <%= f.time_field :timeout %>
    </div>

    <div>
      <%= f.label :depth, 'Max. Depth' %>
      <%= f.number_field :depth %>
    </div>

    <div>
      <%= f.label :air_start, 'Starting Air' %>
      <%= f.number_field :air_start %>
    </div>

    <div>
      <%= f.label :air_end, 'Ending Air' %>
      <%= f.number_field :air_end %>
    </div>

    <div>
      <%= f.label :nitrox, 'Nitrox' %>
      <%= f.number_field :nitrox %>
    </div>

    <div>
      <%= f.label :temperature, 'Temperature' %>
      <%= f.number_field :temperature %>
    </div>

    <div>
      <%= f.label :weight, 'Weight' %>
      <%= f.number_field :weight %>
    </div>

    <div>
      <%= f.label :computer, 'Dive Computer' %>
      <%= f.text_field :computer %>
    </div>

    <div>
      <%= f.submit "Add new dive" %>
    </div>
  <% end %>
</div>

app/views/dives/show.html.erb
<div class="container">
  <div class="jumbotron">
    <center><h1>SCUBA DIVES</h1></center>
    <p>...</p>
  </div>
<p><center>
  <strong>#</strong>
  <%= @dive.number %> |
  <strong>Date</strong>
  <%= @dive.date.strftime('%d %b %y') %>
  <br>
  <strong>Dive Site</strong>
  <%= link_to @dive.place.sites, place_path(@dive.place_id) %>

  <br>
  <strong>Time In</strong>
  <%= @dive.timein.strftime('%H:%M') %> |
  <strong>Time Out</strong>
  <%= @dive.timeout.strftime('%H:%M') %> |
  <strong>Dive Depth</strong>
  <%= @dive.depth %>

  <br>
  <strong>Starting Air Pressure</strong>
  <%= @dive.air_start %> PSI |
  <strong>Ending Air Pressure</strong>
  <%= @dive.air_end %> PSI |
  <strong>Nitrox</strong>
  <%= @dive.nitrox %>

  <br>
  <strong>Temperature</strong>
  <%= @dive.temperature %> degrees |
  <strong>Weights</strong>
  <%= @dive.weight %> lbs |
  <strong>Computer Used</strong>
  <%= @dive.computer %>
</p>

<%= link_to "Edit", edit_dive_path(@dive) %> |
<%= link_to "Delete", dive_path, method: :delete, data: {
  confirm: "Are you sure you want to delete this dive?"} %> |
<%= link_to "Back", 'javascript:history.go(-1);' %>
</center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DivelogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><strong>SCUBA<strong> online logbook</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/dives"><span class="glyphicon glyphicon-home"></span> Dive Log</a></li>
        <li><a href="/places"><span class="glyphicon glyphicon-globe"></span> Dive Sites</a></li>
        <li><a href="/users"><span class="glyphicon glyphicon-user"></span> Users</a></li>
        <li>
          <% if logged_in? %>
            <%= link_to 'Logout', logout_path,:class=>' glyphicon glyphicon-remove' %>
          <% else %>
            <%= link_to 'Login', new_session_path,:class=>' glyphicon glyphicon-ok' %>
          <% end %> </li>

      </ul>
    </div>
  </nav>

  <% if flash[:success] %>
    <div class="alert alert-success"><%= flash[:success] %> </div>
    <% elsif flash[:failure] %>
    <div class="alert alert-danger"><%= flash[:failure] %> </div>
  <% end %>

<script> $('.alert').delay(2000).slideUp() </script>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<h1><center>EDIT THIS DIVE SITE</center></h1>

<%= form_for @place do |f| %>
  <div>
    <%= f.label :city, 'City' %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :sites, 'Site' %>
    <%= f.text_field :sites %>
  </div>

  <div>
    <%= f.submit "Submit changes" %>
  </div>
<% end %>

app/views/places/index.html.erb
<h1><center>LIST OF DIVE SITES</h1></center>
<center><%= link_to "Add new Dive Site", new_place_path %>

<% @places.reverse.each do |p| %>
  <h3><%= p.city %> |
    <%= link_to p.sites, place_path(p) %> |
    <%= p.dives.count %> Dives</h3>
  <hr>
<% end %>
</center>

app/views/places/new.html.erb
<h1><center>ADD NEW DIVE SITE</center></h1>

<%= form_for @place do |f| %>
  <div>
    <%= f.label :city, 'City' %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :sites, 'Site' %>
    <%= f.text_field :sites %>
  </div>

  <div>
    <%= f.submit "Add new site" %>
  </div>
<% end %>

app/views/places/show.html.erb
<h1><center><%= @place.sites %></center></h1>

<div>
  <center>
    <strong><%= @place.city %></strong>

  </center>
</div>

<div>
  <center>
    <%= link_to "Edit", edit_place_path(@place) %> |
    <%= link_to "Delete", place_path, method: :delete, data: {
      confirm: "Are you sure you want to delete this dive site?"} %> |
    <%= link_to "Back", 'javascript:history.go(-1);' %>

  </center>
</div>

app/views/users/edit.html.erb
<h1><center>EDIT THIS USER</center></h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :certification, 'Certification' %>
    <%= f.text_field :certification %>
  </div>

  <div>
    <%= f.label :avatar, 'Profile Picture' %>
    <%= f.file_field :avatar %>
  </div>

  <div>
    <%= f.submit "Submit changes!" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1><center>SCUBA DIVE BUDDIES</center></h1>
<center><%= link_to "Add new buddies", new_user_path %></center>

<center>
  <% @users.each do |u| %>
    <%= image_tag u.avatar.url(:thumb) %>
    <h3><%= link_to u.name, user_path(u) %></h3>
    <h4><%= u.email %></h4>
    <hr>
  <% end %>
</center>

app/views/users/new.html.erb
<h1><center>ADD NEW USER</center></h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :certification, 'Certification' %>
    <%= f.text_field :certification %>
  </div>

  <div>
    <%= f.label :avatar, 'Profile Picture' %>
    <%= f.file_field :avatar %>
  </div>

  <div>
    <%= f.submit "Add new user" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron">
    <center><h1>Welcome</h1></center>
    <p>...</p>
  </div>
  <!-- <h3><%= @user.name %></h3> -->
  <div>
    <%= image_tag @user.avatar.url(:medium) %>
  </div>

  <div>
  <h1><%= @user.name %></h1>
  <h3>Number of dives: <% %></h3>
  <h3>Max Depth: <% %></h3>

  <%= link_to "Edit", edit_user_path %> |
  <%= link_to "Delete", user_path, method: :delete, data: {
    confirm: "Are you sure you want to delete this user?"} %> |
  <%= link_to "Dive Log", dives_path %> |
  <%= link_to "Back", 'javascript:history.go(-1);' %>
  </div>
</div>